### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by yangdaowu** [kaparoo/Conv-TasNet#1]
Hello, I'm glad to see the program you proposed. I encountered a problem during training. My computer memory is too small to find batch_ Where is size. Could you help me?

**Comment by kaparoo** [comment]
I am really sorry for this late reply. I used Intel(R) Xeon(R) Gold 5150 CPU (RAM 177GB) and Tesla V100 (VRAM 32GB) for training the model. In other words, the default values of the parameters, such as `num_songs`, `num_samples`, `max_decoded` and `repeat` (see `main.py` and `dataset.py`) are fitted with my hardware environment. So I suggest to reduce the values of them (especially `repeat` which refers the batch_size in each epoch). Thanks for your attention!
